<a href="https://colab.research.google.com/github/Abhilash-Bee/DeepLearningCertification/blob/main/00_TensorFlow_Fundamentals_Exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🛠 **00. TensorFlow Fundamentals Exercises**

1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

---

---

## **0. Importing TensorFlow**

In [ ]:
import tensorflow as tf

tf.__version__

'2.15.0'

---

---

## **1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().**



In [ ]:
# Scalar

scalar = 7
scalar

7

In [ ]:
# Vector

vector = [8, 13]
vector

[8, 13]

In [ ]:
# Matrix

matrix = [[8, 13],
          [10, 5]]
matrix

[[8, 13], [10, 5]]

In [ ]:
# Scalar-Tensor

scalar_tensor = tf.constant(scalar)
scalar_tensor

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Vector-Tensor

vector_tensor = tf.constant(vector)
vector_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 8, 13], dtype=int32)>

In [ ]:
# Matrix-Tensor

matrix_tensor = tf.constant(matrix)
matrix_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 8, 13],
       [10,  5]], dtype=int32)>

---

---

## **2. Find the shape, rank and size of the tensors you created in 1.**

In [ ]:
print('Scalar Shape:', scalar_tensor.shape)
print('Scalar Rank:', scalar_tensor.ndim)
print('Scalar size:', tf.size(scalar_tensor))

Scalar Shape: ()
Scalar Rank: 0
Scalar size: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print('Vector Shape:', vector_tensor.shape)
print('Vector Rank:', vector_tensor.ndim)
print('Vector size:', tf.size(vector_tensor))

Vector Shape: (2,)
Vector Rank: 1
Vector size: tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
print('Matrix Shape:', matrix_tensor.shape)
print('Matrix Rank:', matrix_tensor.ndim)
print('Matrix size:', tf.size(matrix_tensor).numpy())

Matrix Shape: (2, 2)
Matrix Rank: 2
Matrix size: 4


---

---

## **3. Create two tensors containing random values between 0 and 1 with shape [5, 300].**

In [ ]:
tf.random.set_seed(8)
rand_tensor_1 = tf.random.normal([5, 300])
rand_tensor_1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 1.2074401 , -0.7452462 ,  0.6908678 , ...,  0.41348934,
         1.0111853 , -0.5068622 ],
       [-0.615032  ,  1.0809565 ,  1.0717989 , ...,  1.2365917 ,
        -0.9548575 ,  0.4210502 ],
       [ 0.20328137, -0.41216978,  0.39604047, ...,  0.73841554,
        -0.5433401 , -0.19178566],
       [-0.67259544, -0.01823891,  1.1740032 , ..., -0.00382315,
         1.6092392 , -1.3606751 ],
       [-0.07399517,  0.15060243, -1.4232525 , ...,  0.91519403,
         0.7762883 , -0.9586654 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(13)
rand_tensor_2 = tf.random.normal([5, 300])
rand_tensor_2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 0.46733698,  0.89927393, -0.78262424, ..., -0.00339889,
        -1.003618  , -1.3988328 ],
       [-0.8889128 ,  0.3825111 ,  0.23511857, ..., -0.8417241 ,
         0.19115192,  1.6598426 ],
       [ 0.39654583,  1.3194978 ,  1.6494288 , ...,  0.6034325 ,
        -0.20702732, -0.58929247],
       [-0.08622172, -1.0301651 , -1.0771402 , ...,  0.81814975,
         1.1996921 ,  0.574482  ],
       [ 1.891347  ,  0.6549452 ,  0.6319449 , ...,  1.8122883 ,
         1.7424241 ,  1.9001238 ]], dtype=float32)>

---

---

## **4. Multiply the two tensors you created in 3 using matrix multiplication.**

In [ ]:
rand_tensor_3 = rand_tensor_1 * rand_tensor_2
rand_tensor_3

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 5.6428140e-01, -6.7018044e-01, -5.4068989e-01, ...,
        -1.4054053e-03, -1.0148437e+00,  7.0901549e-01],
       [ 5.4670984e-01,  4.1347787e-01,  2.5199983e-01, ...,
        -1.0408690e+00, -1.8252285e-01,  6.9887704e-01],
       [ 8.0610380e-02, -5.4385716e-01,  6.5324056e-01, ...,
         4.4558391e-01,  1.1248624e-01,  1.1301785e-01],
       [ 5.7992339e-02,  1.8789090e-02, -1.2645661e+00, ...,
        -3.1279081e-03,  1.9305916e+00, -7.8168339e-01],
       [-1.3995056e-01,  9.8636337e-02, -8.9941710e-01, ...,
         1.6585954e+00,  1.3526235e+00, -1.8215829e+00]], dtype=float32)>

In [ ]:
rand_tensor_4 = tf.multiply(rand_tensor_1, rand_tensor_2)
rand_tensor_4

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[ 5.6428140e-01, -6.7018044e-01, -5.4068989e-01, ...,
        -1.4054053e-03, -1.0148437e+00,  7.0901549e-01],
       [ 5.4670984e-01,  4.1347787e-01,  2.5199983e-01, ...,
        -1.0408690e+00, -1.8252285e-01,  6.9887704e-01],
       [ 8.0610380e-02, -5.4385716e-01,  6.5324056e-01, ...,
         4.4558391e-01,  1.1248624e-01,  1.1301785e-01],
       [ 5.7992339e-02,  1.8789090e-02, -1.2645661e+00, ...,
        -3.1279081e-03,  1.9305916e+00, -7.8168339e-01],
       [-1.3995056e-01,  9.8636337e-02, -8.9941710e-01, ...,
         1.6585954e+00,  1.3526235e+00, -1.8215829e+00]], dtype=float32)>

---

---

## **5. Multiply the two tensors you created in 3 using dot product.**

In [ ]:
rand_tensor_5 = rand_tensor_1 @ tf.transpose(rand_tensor_2)
rand_tensor_5

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-27.844341 ,   8.376965 ,   6.693235 , -30.54904  , -20.347622 ],
       [ 16.756718 ,  -7.024115 ,  -5.0225754,   8.68558  ,  20.473629 ],
       [ -7.4475946,  16.062185 ,   4.002384 , -15.966463 , -47.850693 ],
       [ 25.589417 ,   9.014551 , -12.429403 , -13.239283 ,  23.374681 ],
       [ -0.828989 , -22.863894 ,  24.36324  ,  17.802435 ,   2.923245 ]],
      dtype=float32)>

In [ ]:
rand_tensor_6 = tf.matmul(rand_tensor_1, rand_tensor_2, transpose_b=True)
rand_tensor_6

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-27.844341 ,   8.376965 ,   6.693235 , -30.54904  , -20.347622 ],
       [ 16.756718 ,  -7.024115 ,  -5.0225754,   8.68558  ,  20.473629 ],
       [ -7.4475946,  16.062185 ,   4.002384 , -15.966463 , -47.850693 ],
       [ 25.589417 ,   9.014551 , -12.429403 , -13.239283 ,  23.374681 ],
       [ -0.828989 , -22.863894 ,  24.36324  ,  17.802435 ,   2.923245 ]],
      dtype=float32)>

---

---

## **6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].**

In [ ]:
tf.random.set_seed(8)
rand_tensor_3d = tf.random.normal([224, 224, 3])
rand_tensor_3d

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[ 1.2074401e+00, -7.4524617e-01,  6.9086778e-01],
        [-7.6359880e-01, -2.4725451e+00,  5.8341402e-01],
        [ 2.7248889e-01, -4.5308730e-01,  5.9562445e-01],
        ...,
        [ 3.8274556e-01, -5.8457148e-01, -3.3245701e-01],
        [-1.2835133e+00,  1.8631322e+00, -2.2772641e+00],
        [-4.1349369e-01,  6.7511153e-01,  3.1716865e-01]],

       [[ 5.6904036e-01,  7.9601842e-01, -5.5805594e-01],
        [-2.5748613e+00,  8.8135904e-01, -1.5871291e-01],
        [ 2.0767291e+00,  5.1848781e-01,  8.0432779e-01],
        ...,
        [-1.0550995e+00, -7.4551076e-01, -2.4144816e-01],
        [-3.8414150e-01, -1.9853790e+00, -7.9983521e-01],
        [-1.4019266e-01, -1.8271549e+00, -4.3548155e-01]],

       [[ 7.4505967e-01, -7.8544691e-02, -6.1164266e-01],
        [-3.8983086e-01,  1.5153303e+00,  6.5550292e-01],
        [ 5.0580347e-01, -5.0000471e-01, -1.3863361e+00],
        ...,
        [ 3.7148711e-01,  7.3761

---

---

## **7. Find the min and max values of the tensor you created in 6 along the first axis.**

In [ ]:
# Minimum values in rand_tensor_3d along first axis (axis=1)

min = tf.reduce_min(rand_tensor_3d, axis=1)
min

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[-2.6111567, -2.6206064, -2.6236355],
       [-2.8915224, -2.6960318, -2.795175 ],
       [-2.6187434, -3.0560741, -2.668006 ],
       [-3.718246 , -2.4147823, -2.647766 ],
       [-2.6776953, -2.57523  , -2.9417646],
       [-2.7661216, -2.757551 , -2.5072596],
       [-2.2377243, -3.6505606, -2.94296  ],
       [-2.9566748, -2.414771 , -2.2353952],
       [-2.5377264, -2.2252197, -2.4405742],
       [-2.9242606, -2.6130486, -3.0380712],
       [-2.6361456, -2.7280865, -2.8174565],
       [-2.9253259, -2.8901384, -2.3577545],
       [-2.3066413, -2.6695178, -2.4072125],
       [-4.116674 , -3.487861 , -2.609929 ],
       [-2.9804802, -2.4455054, -2.878742 ],
       [-2.641624 , -3.1212175, -2.477215 ],
       [-2.3328173, -2.0451956, -3.1921043],
       [-2.1251028, -2.4823017, -2.3906775],
       [-2.3787034, -3.0225828, -2.9581914],
       [-2.7172143, -2.4411905, -3.1289918],
       [-2.9055853, -2.9239829, -2.298721 ],
     

In [ ]:
# Maximum values in rand_tensor_3d along first axis (axis=1)

max = tf.reduce_max(rand_tensor_3d, axis=1)
max

<tf.Tensor: shape=(224, 3), dtype=float32, numpy=
array([[3.6931124, 3.875815 , 2.3918061],
       [2.5597692, 2.732857 , 3.3285372],
       [3.0758047, 2.9977002, 3.0356796],
       [2.8015184, 3.4888377, 2.7154498],
       [2.572701 , 2.7158961, 2.8254821],
       [2.8526256, 2.3707669, 2.5694616],
       [2.7136188, 3.49579  , 3.0577245],
       [2.3453343, 2.525589 , 3.4414928],
       [2.392164 , 2.5641289, 2.7615914],
       [2.2840145, 2.5153866, 2.7226377],
       [2.507508 , 3.117597 , 3.1905518],
       [2.6446292, 3.3391933, 2.975334 ],
       [2.3754334, 2.7091608, 3.0686724],
       [2.704627 , 2.781787 , 2.370723 ],
       [3.4069333, 2.3803294, 3.0029488],
       [2.982242 , 2.8345435, 2.7907505],
       [2.8016512, 2.920856 , 2.75311  ],
       [2.718816 , 2.8583326, 2.416334 ],
       [2.8361244, 2.211527 , 2.9272783],
       [3.1569858, 3.1693532, 2.8124444],
       [2.8450878, 2.2249713, 2.8822248],
       [2.837734 , 2.21551  , 2.6272318],
       [2.4533908, 2.96772

---

---

## **8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].**

In [ ]:
tf.random.set_seed(13)
rand_tensor_4d = tf.random.normal([1, 224, 224, 3])
rand_tensor_4d.shape

TensorShape([1, 224, 224, 3])

In [ ]:
rand_squeezed_3d = tf.squeeze(rand_tensor_4d)
rand_squeezed_3d.shape

TensorShape([224, 224, 3])

---

---

## **9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.**

In [ ]:
tf.random.set_seed(20)
random_numbers = tf.range(0, 11)
random_numbers = tf.random.shuffle(random_numbers)
random_numbers

<tf.Tensor: shape=(11,), dtype=int32, numpy=array([ 2,  0, 10,  6,  7,  5,  8,  3,  9,  1,  4], dtype=int32)>

In [ ]:
max_ind = tf.argmax(random_numbers)
max_ind

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
random_numbers[tf.argmax(random_numbers)]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

---

---

## **10. One-hot encode the tensor you created in 9.**

In [ ]:
tf.one_hot(random_numbers, depth=10)

<tf.Tensor: shape=(11, 10), dtype=float32, numpy=
array([[0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(random_numbers, depth=5)

<tf.Tensor: shape=(11, 5), dtype=float32, numpy=
array([[0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.]], dtype=float32)>

In [ ]:
tf.one_hot(random_numbers, depth=10, on_value='A', off_value='L', dtype=tf.string)

<tf.Tensor: shape=(11, 10), dtype=string, numpy=
array([[b'L', b'L', b'A', b'L', b'L', b'L', b'L', b'L', b'L', b'L'],
       [b'A', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L'],
       [b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L'],
       [b'L', b'L', b'L', b'L', b'L', b'L', b'A', b'L', b'L', b'L'],
       [b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'A', b'L', b'L'],
       [b'L', b'L', b'L', b'L', b'L', b'A', b'L', b'L', b'L', b'L'],
       [b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'A', b'L'],
       [b'L', b'L', b'L', b'A', b'L', b'L', b'L', b'L', b'L', b'L'],
       [b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'A'],
       [b'L', b'A', b'L', b'L', b'L', b'L', b'L', b'L', b'L', b'L'],
       [b'L', b'L', b'L', b'L', b'A', b'L', b'L', b'L', b'L', b'L']],
      dtype=object)>

---

---

# **📖 00. TensorFlow Fundamentals Extra-curriculum**

* Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.

* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
 * How would you calculate your grocery bill for the month and for the year using tensors?

* Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
 * Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?

* Watch the video "What's a tensor?" - a great visual introduction to many of the concepts we've covered in this notebook.

---

---